CXX = /usr/uhome/aurora/4gi/nlabhpg/.llvm-trunk-ncc2-glibc/bin/clang++

# protoc compiler, from Protocol Buffers build
PROTOC=/usr/uhome/aurora/4gi/nlabhpg/malon/x86/protobuf-clang-install/bin/protoc

# Top directory of Pytorch source tree (.proto files are beneath here)
CAFFE2_PROTO=/usr/uhome/aurora/4gi/nlabhpg/malon/x86/pytorch

# Some headers from Pytorch source tree, from Protocol Buffers,
# and from top level of caffe2_cpp_tutorial
CAFFE2_INC = -I/usr/uhome/aurora/4gi/nlabhpg/malon/x86/pytorch -I/usr/uhome/aurora/4gi/nlabhpg/malon/x86/pytorch/aten/src -I/usr/uhome/aurora/4gi/nlabhpg/malon/x86/pytorch/build_x86 -I/usr/uhome/aurora/4gi/nlabhpg/malon/x86/pytorch/build_x86/caffe2/proto -I/usr/uhome/aurora/4gi/nlabhpg/malon/x86/protobuf-clang-install/include -I../../../include

CXX_FLAGS = $(CAFFE2_INC) -g -std=c++11 -fPIC -DCAFFE2_API=""

# Libraries from pytorch/caffe2 build, protocol buffers, and clang
LIB_DIRS = -L/usr/uhome/aurora/4gi/nlabhpg/malon/x86/pytorch/build_x86/lib -L/usr/uhome/aurora/4gi/nlabhpg/malon/x86/protobuf-clang-install/lib -Wl,-rpath=/usr/uhome/aurora/4gi/nlabhpg/malon/x86/pytorch/build_x86/lib -Wl,-rpath=/usr/uhome/aurora/4gi/nlabhpg/malon/x86/protobuf-clang-install/lib -L/usr/uhome/aurora/4gi/nlabhpg/.llvm-trunk-ncc2-glibc/lib -Wl,-rpath=/usr/uhome/aurora/4gi/nlabhpg/.llvm-trunk-ncc2-glibc/lib
LD_FLAGS = -Wl,--allow-multiple-definition $(LIB_DIRS) -fPIC

all: utillibs.so

model.pb.h model.pb.cc: model.proto
	$(PROTOC) --proto_path=$(CAFFE2_PROTO) --proto_path=. --cpp_out=. model.proto

lib_objects = blob.o tensor.o table.o net.o net_gradient.o net_operator.o net_serial.o progress.o model.pb.o model.o

$(lib_objects): %.o : %.cc
	$(CXX) $(CXX_FLAGS) -c $<

utillibs.so: $(lib_objects)
	$(CXX) $(LD_FLAGS) -shared -o utillibs.so $(lib_objects)

clean:
	rm -f utillibs.so $(lib_objects)
