CXX = /usr/uhome/aurora/4gi/nlabhpg/.llvm-trunk-ncc2-glibc/bin/clang++
CAFFE2_INC = -I/usr/uhome/aurora/4gi/nlabhpg/malon/aurora/pytorch-ncc2-clang-shared -I/usr/uhome/aurora/4gi/nlabhpg/malon/aurora/pytorch-ncc2-clang-shared/aten/src -I/usr/uhome/aurora/4gi/nlabhpg/malon/aurora/pytorch-ncc2-clang-shared/build_ve -I/usr/uhome/aurora/4gi/nlabhpg/malon/aurora/protobuf-clang9-shared-install/include -I../../../include
CXX_FLAGS = --target=ve-linux -fno-vectorize -fno-slp-vectorize -fno-crash-diagnostics $(CAFFE2_INC) -g
LIB_DIRS = -L/usr/uhome/aurora/4gi/nlabhpg/malon/aurora/pytorch-ncc2-clang-shared/build_ve/lib -L/usr/uhome/aurora/4gi/nlabhpg/malon/aurora/protobuf-clang9-shared-install/lib -L/opt/nec/ve/nlc/1.0.0/lib -L/opt/nec/ve/nfort/2.1.22/lib -Wl,-rpath=/usr/uhome/aurora/4gi/nlabhpg/malon/aurora/pytorch-ncc2-clang-shared/build_ve/lib -Wl,-rpath=/usr/uhome/aurora/4gi/nlabhpg/malon/aurora/protobuf-clang9-shared-install/lib -L/usr/uhome/aurora/4gi/nlabhpg/.llvm-trunk-ncc2-glibc/lib/clang/9.0.0/lib/linux/ve -L/usr/uhome/aurora/4gi/nlabhpg/malon/aurora/leveldb-install/lib -L/usr/uhome/aurora/4gi/nlabhpg/malon/aurora/snappy-install/lib
LD_FLAGS = -Wl,--allow-multiple-definition -Wl,-z,max-page-size=0x200000 -Wl,-rpath=/usr/uhome/aurora/4gi/nlabhpg/.llvm-trunk-ncc2-glibc/lib/clang/9.0.0/lib/linux/ve $(LIB_DIRS)
FORT = /opt/nec/ve/bin/nfort

all: mnist intro

mnist.o: mnist.cc
	$(CXX) $(CXX_FLAGS) -c mnist.cc

mnist: mnist.o ../util/utillibs.so
	$(FORT) $(LD_FLAGS) -o mnist mnist.o ../util/utillibs.so -lcaffe2 -lcaffe2_protos -lprotobuf -lcpuinfo -lclog -lc10 -lleveldb -lsnappy -llapack -lcblas -lblas_openmp -lomp -lpthread -lvastfp -lc++ -lc++abi -ldl -lunwind  /opt/nec/ve/nfort/2.1.24/lib/async_io.o /opt/nec/ve/nfort/2.1.24/lib/libnfort.a -lveio

intro.o: intro.cc
	$(CXX) $(CXX_FLAGS) -c intro.cc

intro: intro.o
	$(FORT) $(LD_FLAGS) -o intro intro.o -lcaffe2 -lcaffe2_protos -lprotobuf -lcpuinfo -lclog -lc10 -llapack -lcblas -lblas_openmp -lomp -lpthread -lvastfp -lc++ -lc++abi -ldl -lunwind  /opt/nec/ve/nfort/2.1.24/lib/async_io.o /opt/nec/ve/nfort/2.1.24/lib/libnfort.a -lveio

clean:
	rm -f mnist mnist.o intro intro.o
